autoInstallPeers: true

saveExact: true

shamefullyHoist: true

strictPeerDependencies: false

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  '@typescript-eslint/types': 8.45.0
  '@typescript-eslint/utils': 8.45.0
  is-core-module: 'npm:@no-shims/is-core-module'
