autoInstallPeers: true

saveExact: true

shamefullyHoist: true

strictPeerDependencies: false

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  'is-core-module': 'npm:@no-shims/is-core-module'
