autoInstallPeers: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@eslint-community/eslint-plugin-eslint-comments'
  - eslint-plugin-de-morgan
  - globals

overrides:
  is-core-module: 'npm:@no-shims/is-core-module'

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

saveExact: true

shamefullyHoist: true

strictPeerDependencies: false
